# docker-compose.yml
version: '3'
services:
    web:
        build: .
        tty: true
        restart: always
        command: python manage.py migrate && python manage.py runserver 0.0.0.0:8001
        ports:
            - "8001:8000"
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - .:/code
    
    db:
        image: postgres
        restart: always
        env_file:
            - .env
        volumes:
            - pg_data:/var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
  
    redis:
        image: redis
        ports:
            - "6379:6379"
    celery:
        build: .
        restart: always
        tty: true
        command: celery -A config worler -l INFO
        depends_on:
            - web
            - redis

    celery_beat:
        build: .
        restart: always
        tty: true
        command: celery -A config beat -l INFO -S django
        depends_on:
            - web
            - redis

volumes:
    pg_data:
 